#!/usr/bin/env python3
"""Generate worlds/iris_field_vision.sdf: a dense, PBR-lit, grass-textured field for the vision
demos. Self-contained; re-run to tune density/quality (run scripts/gen_textures.py first if textures
changed). Paths are resolved relative to this file (no machine paths)."""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
WORLD = os.path.join(HERE, "..", "worlds", "iris_field_vision.sdf")
# Repo-local trees. Fuel models look better, but a world that downloads anything at
# launch stalls on a slow link and fails outright offline, so keep it self-contained.
OAK = "model://tree_oak"
PINE = "model://tree_pine"

HEADER = '''<?xml version="1.0" ?>
<!-- Realistic outdoor field for vision demos (search / find / approach / precision-land).
     iris_with_gimbal + ArduPilotPlugin (udp:9002) + NavSat, on a PBR grass-textured field with
     trees, buildings, roads and cars. World name stays "iris_runway" so the camera-stream topic
     is unchanged. GENERATED by scripts/gen_field_world.py (edit there, not here).
     Grass/road tiles are repo-local PBR models (textures from scripts/gen_textures.py,
     ogre2-safe); trees are repo-local too, so the only asset fetched at launch is the walking
     person's Fuel mesh (once, then cached). Launch with GZ_SIM_RESOURCE_PATH including
     ardupilot_gazebo/models and this repo's models. -->
<sdf version="1.9">
  <world name="iris_runway">
    <physics name="1ms" type="ignore">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>

    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-navsat-system" name="gz::sim::systems::NavSat"/>

    <!-- daylight + a sky + light distance fog for depth; bright enough for colour/ArUco detection -->
    <scene>
      <ambient>0.55 0.55 0.58 1</ambient>
      <background>0.7 0.8 0.95</background>
      <sky></sky>
      <shadows>true</shadows>
      <fog><type>linear</type><color>0.78 0.84 0.92 1</color><density>0.0016</density>
        <start>60</start><end>400</end></fog>
    </scene>

    <spherical_coordinates>
      <latitude_deg>-35.363262</latitude_deg>
      <longitude_deg>149.165237</longitude_deg>
      <elevation>584</elevation>
      <heading_deg>0</heading_deg>
      <surface_model>EARTH_WGS84</surface_model>
    </spherical_coordinates>

    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>1.0 0.98 0.92 1</diffuse>
      <specular>0.4 0.4 0.38 1</specular>
      <attenuation>
        <range>2000</range><constant>0.9</constant><linear>0.005</linear><quadratic>0.0005</quadratic>
      </attenuation>
      <direction>-0.4 0.25 -0.88</direction>
    </light>

    <!-- collision base (invisible); the visible far ground is the textured far_field plane
         so the horizon shows farmland variation instead of a flat colour. -->
    <model name="ground">
      <static>true</static>
      <link name="link">
        <collision name="c">
          <geometry><plane><normal>0 0 1</normal><size>2000 2000</size></plane></geometry>
        </collision>
      </link>
    </model>
    <include>
      <name>far_ground</name>
      <pose>0 0 0.003 0 0 0</pose>
      <uri>model://far_field</uri>
    </include>

    <include>
      <uri>model://iris_with_gimbal</uri>
      <pose degrees="true">0 0 0.195 0 0 90</pose>
    </include>

    <!-- ==== search / land targets ==== -->
    <model name="red_pad">
      <static>true</static>
      <pose>0 10 0.03 0 0 0</pose>
      <link name="l"><visual name="v">
        <geometry><box><size>3 3 0.04</size></box></geometry>
        <material><ambient>1 0 0 1</ambient><diffuse>1 0 0 1</diffuse><emissive>0.4 0 0 1</emissive></material>
      </visual></link>
    </model>
    <include>
      <uri>model://aruco_marker</uri>
      <pose>0 3 0.03 0 0 0</pose>
    </include>
    <model name="blue_box">
      <static>true</static>
      <pose>10 0 1 0 0 0</pose>
      <link name="l"><visual name="v">
        <geometry><box><size>2 2 2</size></box></geometry>
        <material><ambient>0 0 1 1</ambient><diffuse>0 0 1 1</diffuse>
          <pbr><metal><roughness>0.6</roughness><metalness>0.0</metalness></metal></pbr></material>
      </visual></link>
    </model>
    <model name="yellow_box">
      <static>true</static>
      <pose>-8 -6 1 0 0 0</pose>
      <link name="l"><visual name="v">
        <geometry><box><size>2 2 2</size></box></geometry>
        <material><ambient>1 1 0 1</ambient><diffuse>1 1 0 1</diffuse>
          <pbr><metal><roughness>0.6</roughness><metalness>0.0</metalness></metal></pbr></material>
      </visual></link>
    </model>
'''

# A walking person (COCO 'person') for the object-follow demo: paces a 14 m N-S line at ~1 m/s on
# an open grass strip (x=6, clear of the target boxes), looping. Skin/animation are the pre-cached
# Fuel 'Mingfei/actor' walk.dae; z=1.0 puts the feet on the ground (matches gz's actor.sdf example).
_WALK = "https://fuel.gazebosim.org/1.0/Mingfei/models/actor/tip/files/meshes/walk.dae"
PERSON = f'''    <!-- ==== moving target: a walking person for object-detection follow ==== -->
    <actor name="person_walking">
      <skin><filename>{_WALK}</filename><scale>1.0</scale></skin>
      <animation name="walk"><filename>{_WALK}</filename><interpolate_x>true</interpolate_x></animation>
      <script>
        <loop>true</loop><delay_start>0.0</delay_start><auto_start>true</auto_start>
        <trajectory id="0" type="walk" tension="0.6">
          <waypoint><time>0</time><pose>6 6 1.0 0 0 1.5708</pose></waypoint>
          <waypoint><time>14</time><pose>6 20 1.0 0 0 1.5708</pose></waypoint>
          <waypoint><time>15</time><pose>6 20 1.0 0 0 -1.5708</pose></waypoint>
          <waypoint><time>29</time><pose>6 6 1.0 0 0 -1.5708</pose></waypoint>
          <waypoint><time>30</time><pose>6 6 1.0 0 0 1.5708</pose></waypoint>
        </trajectory>
      </script>
    </actor>
'''

FOOTER = "\n  </world>\n</sdf>\n"

# --- grass tile grid (visual field texture), on the collision base ---
# Rotating tiles by 0/90/180/270 and mixing in worn tiles breaks the repeating-texture look
# from altitude; the textures are tileable so rotated neighbours still read as continuous field.
# Spatial-hash selection (not a linear formula) so worn tiles don't line up in diagonal chains.
grass = []
N, STEP = 12, 15                     # 12x12 tiles of 15 m -> ~180 m of textured field, ±90 m
start = -(N - 1) / 2 * STEP
for ix in range(N):
    for iy in range(N):
        x = start + ix * STEP
        y = start + iy * STEP
        h = (ix * 73856093) ^ (iy * 19349663)
        yaw = ((h >> 4) % 4) * 90
        uri = "grass_tile_worn" if h % 7 == 0 else "grass_tile"
        grass.append(f'    <include><name>g_{ix}_{iy}</name>'
                     f'<pose degrees="true">{x:.1f} {y:.1f} 0.01 0 0 {yaw}</pose>'
                     f'<uri>model://{uri}</uri></include>')

# --- scenery, all with max(|x|,|y|) >= 24 so the ±20 m search area stays clear ---
# Buildings, towers, poles and walls carry COLLISION geometry: flying into one is a real crash,
# which is the point -- the world doubles as the obstacle course for avoidance work.
# Canonical obstacle for tests: radio tower at (30, 0) = 30 m EAST of spawn, 28 m tall
# ("fly 45 m east at 15 m" crosses it).
trees = [(26, 24), (30, -26), (-28, 26), (-26, -28), (40, 10), (42, -14), (-40, 12), (-42, -10),
         (12, -40), (-14, 40), (48, 36), (-46, 34), (46, -38), (-44, -40), (55, 2), (-56, 4),
         (6, 52), (-8, -54), (60, 24), (-60, -22), (24, 58), (-22, -60), (36, -50), (-38, 50),
         (34, 14), (-34, 16), (16, 34), (-16, -36), (52, 14), (-52, -14), (14, -52), (-12, 56),
         (64, 8), (-64, -4), (8, 64), (-4, -64), (44, 46), (-42, 44), (48, -46), (-50, -48)]
buildings = [(34, 30, 9, 8, 7), (46, 34, 11, 9, 10), (30, 46, 8, 11, 6), (52, 44, 12, 10, 12),
             (40, 54, 9, 9, 8), (28, 40, 6, 6, 5), (58, 30, 10, 12, 14), (44, 22, 7, 7, 6),
             (-38, -32, 10, 8, 7), (-30, -44, 8, 9, 9), (-48, -30, 9, 7, 11),
             (-40, 36, 8, 8, 6), (-54, 24, 10, 8, 9), (38, -34, 9, 7, 8), (54, -24, 8, 10, 7)]
# roads are chains of textured road_tile segments (15x7 m, axis along x): (cx, cy, yaw_deg, n)
roads = [(0, 26, 0, 10), (0, -30, 0, 10), (26, 0, 90, 10)]
# cars sit in lanes (lane centre = road centre +/- 1.75 m), heading with the lane
cars = [(12, 24.25, 0, 0.62, 0.07, 0.07), (-16, 27.75, 180, 0.75, 0.75, 0.78),
        (34, 24.25, 0, 0.10, 0.18, 0.45), (-30, -28.25, 0, 0.12, 0.12, 0.13),
        (8, -31.75, 180, 0.72, 0.55, 0.08), (24.25, -14, 270, 0.55, 0.58, 0.60),
        (27.75, 36, 90, 0.35, 0.08, 0.08), (-42, 24.25, 0, 0.80, 0.80, 0.82),
        (44, -28.25, 0, 0.10, 0.35, 0.15), (27.75, -44, 90, 0.65, 0.60, 0.20)]
bushes = [(24, 30, 1.3), (32, 22, 1.0), (-24, 30, 1.5), (-30, -24, 1.2), (36, -24, 1.4),
          (-24, -34, 1.0), (44, 6, 1.6), (-44, 4, 1.3), (4, 44, 1.2), (-6, -44, 1.5),
          (52, 28, 1.1), (-50, 30, 1.4), (50, -30, 1.2), (-46, -44, 1.6), (16, 56, 1.3),
          (-18, 54, 1.1), (58, -8, 1.5), (-58, -6, 1.0), (28, -36, 1.2), (-28, 38, 1.4),
          (38, 42, 1.0), (-36, -50, 1.3), (60, 16, 1.2), (-60, 12, 1.5), (20, -58, 1.1),
          (-22, 62, 1.3), (66, -18, 1.4), (-66, 20, 1.0)]
rocks = [(28, -22, 0.5), (-26, 24, 0.7), (38, 30, 0.4), (-36, -26, 0.6), (6, -46, 0.5),
         (-4, 48, 0.8), (46, -14, 0.4), (-48, 16, 0.6), (30, 52, 0.5), (-32, -50, 0.7),
         (24, 38, 0.6), (-24, -42, 0.5), (54, 8, 0.7), (-54, -10, 0.4), (10, 58, 0.6),
         (-8, -60, 0.5)]
towers = [(30, 0, 28.0), (0, -40, 22.0)]            # (x, y, height): lattice radio towers
poles = [(-45, 31), (-30, 31), (-15, 31), (0, 31), (15, 31), (45, 31), (60, 31)]
walls = [(-38, -24, 28, 0, 1.8), (-24, 38, 28, 90, 1.8)]   # (cx, cy, length, yaw_deg, height)
pond = (44, -8, 13, 8)                              # (x, y, rx, ry) decorative water


def pbr(rough, metal=0.0):
    return f'<pbr><metal><roughness>{rough}</roughness><metalness>{metal}</metalness></metal></pbr>'


def mat(r, g, b, rough=0.85, metal=0.0):
    return (f'<material><ambient>{r*0.55:.2f} {g*0.55:.2f} {b*0.55:.2f} 1</ambient>'
            f'<diffuse>{r:.2f} {g:.2f} {b:.2f} 1</diffuse>{pbr(rough, metal)}</material>')


def box(name, x, y, z, sx, sy, sz, material, yaw_deg=0):
    return (f'<visual name="{name}"><pose degrees="true">{x} {y} {z} 0 0 {yaw_deg}</pose>'
            f'<geometry><box><size>{sx} {sy} {sz}</size></box></geometry>{material}</visual>')


scenery = ["    <!-- ==== dense scenery: PBR + COLLADA trees, all outside the ±20 m search area ==== -->"]
for i, (x, y) in enumerate(trees):
    uri = PINE if i % 2 else OAK
    yaw = round((i * 0.7) % 3.1, 2)
    scenery.append(f'    <include><name>tree_{i}</name><pose>{x} {y} 0 0 0 {yaw}</pose>'
                   f'<uri>{uri}</uri></include>')


def collide(name, x, y, z, sx, sy, sz):
    return (f'<collision name="{name}"><pose>{x} {y} {z} 0 0 0</pose>'
            f'<geometry><box><size>{sx} {sy} {sz}</size></box></geometry></collision>')


for i, (x, y, sx, sy, h) in enumerate(buildings):
    s = 0.62 + (i % 4) * 0.04
    wall_mat = mat(s, s - 0.04, s - 0.10)
    roof = mat(0.42, 0.25, 0.18, 0.9) if i % 3 == 0 else mat(0.30, 0.30, 0.32, 0.9)
    parts = [box("walls", 0, 0, h / 2, sx, sy, h, wall_mat),
             box("roof", 0, 0, h + 0.15, sx + 0.5, sy + 0.5, 0.3, roof),
             collide("c", 0, 0, h / 2 + 0.15, sx, sy, h + 0.3)]
    for j in range(1 + i % 2):       # rooftop AC units — the detail you see from the air
        ax = (sx / 2 - 1.2) * (1 if (i + j) % 2 else -1)
        ay = (sy / 2 - 1.4) * (1 if j else -1) * 0.6
        parts.append(box(f"ac_{j}", round(ax, 1), round(ay, 1), h + 0.75, 1.3, 1.0, 0.9,
                         mat(0.55, 0.56, 0.58, 0.5, 0.6), yaw_deg=(i * 37) % 90))
    scenery.append(f'    <model name="bldg_{i}"><static>true</static><pose>{x} {y} 0 0 0 0</pose>'
                   f'<link name="l">{"".join(parts)}</link></model>')
for i, (x, y, h) in enumerate(towers):
    steel = mat(0.72, 0.24, 0.20, 0.6, 0.4)          # red-white lattice look
    white = mat(0.85, 0.86, 0.88, 0.6, 0.4)
    parts = [box("mast", 0, 0, h / 2, 1.1, 1.1, h, steel),
             collide("c", 0, 0, h / 2, 1.3, 1.3, h)]
    for j, frac in enumerate((0.35, 0.6, 0.85)):     # crossarms + white bands
        parts.append(box(f"arm_{j}", 0, 0, h * frac, 4.0, 0.35, 0.35, white))
    scenery.append(f'    <model name="tower_{i}"><static>true</static>'
                   f'<pose>{x} {y} 0 0 0 0</pose><link name="l">{"".join(parts)}</link></model>')
for i, (x, y) in enumerate(poles):
    wood = mat(0.30, 0.22, 0.16, 0.95)
    parts = ['<visual name="p"><pose>0 0 4 0 0 0</pose><geometry><cylinder>'
             f'<radius>0.14</radius><length>8</length></cylinder></geometry>{wood}</visual>',
             box("bar", 0, 0, 7.6, 2.4, 0.18, 0.18, wood),
             '<collision name="c"><pose>0 0 4 0 0 0</pose><geometry><cylinder>'
             '<radius>0.2</radius><length>8</length></cylinder></geometry></collision>']
    scenery.append(f'    <model name="pole_{i}"><static>true</static>'
                   f'<pose>{x} {y} 0 0 0 0</pose><link name="l">{"".join(parts)}</link></model>')
for i, (cx, cy, length, yaw, h) in enumerate(walls):
    stone = mat(0.55, 0.52, 0.48, 0.95)
    scenery.append(f'    <model name="wall_{i}"><static>true</static>'
                   f'<pose degrees="true">{cx} {cy} 0 0 0 {yaw}</pose><link name="l">'
                   f'{box("w", 0, 0, h / 2, length, 0.35, h, stone)}'
                   f'{collide("c", 0, 0, h / 2, length, 0.35, h)}</link></model>')
px, py, prx, pry = pond
scenery.append(f'    <model name="pond"><static>true</static><pose>{px} {py} 0.015 0 0 0</pose>'
               f'<link name="l"><visual name="v"><geometry><plane><normal>0 0 1</normal>'
               f'<size>{prx * 2} {pry * 2}</size></plane></geometry>'
               f'<material><ambient>0.05 0.10 0.12 1</ambient><diffuse>0.10 0.22 0.28 1</diffuse>'
               f'<specular>0.6 0.65 0.7 1</specular>{pbr(0.15)}</material></visual></link></model>')
for i, (cx, cy, yaw, n) in enumerate(roads):
    z = 0.02 + i * 0.001             # stagger overlapping roads so intersections don't z-fight
    for j in range(n):
        d = (j - (n - 1) / 2) * 15
        x, y = (cx + d, cy) if yaw == 0 else (cx, cy + d)
        scenery.append(f'    <include><name>road_{i}_{j}</name>'
                       f'<pose degrees="true">{x:.1f} {y:.1f} {z:.3f} 0 0 {yaw}</pose>'
                       f'<uri>model://road_tile</uri></include>')
for i, (x, y, yaw, r, g, b) in enumerate(cars):
    glass = mat(0.10, 0.11, 0.13, 0.25, 0.2)
    tyre = mat(0.08, 0.08, 0.08, 0.95)
    parts = [box("body", 0, 0, 0.55, 4.0, 1.7, 0.55, mat(r, g, b, 0.35, 0.3)),
             box("cabin", -0.2, 0, 1.02, 2.0, 1.5, 0.45, glass)]
    for j, (wx, wy) in enumerate([(1.25, 0.85), (1.25, -0.85), (-1.25, 0.85), (-1.25, -0.85)]):
        parts.append(f'<visual name="w{j}"><pose>{wx} {wy} 0.32 1.5708 0 0</pose>'
                     f'<geometry><cylinder><radius>0.32</radius><length>0.24</length></cylinder>'
                     f'</geometry>{tyre}</visual>')
    scenery.append(f'    <model name="car_{i}"><static>true</static>'
                   f'<pose degrees="true">{x} {y} 0 0 0 {yaw}</pose>'
                   f'<link name="l">{"".join(parts)}</link></model>')
# A MOVING red car (COCO 'car') for the dynamic-chase demo: the VelocityControl system laps it round
# a gentle 10 m-radius circle on open grass SW of spawn (clear of the boxes, the person line at x=6,
# spawn and all scenery). Dynamic + gravity-off + no collision = a kinematic prop that circles
# forever with no external publisher -- the initial twist lives in the plugin. w = v/R gives the
# radius; the start pose sits on the circle facing the tangent so body-x (forward) starts it round.
mcx, mcy, mR, mv = -10.0, -10.0, 10.0, 2.0
mglass, mtyre = mat(0.10, 0.11, 0.13, 0.25, 0.2), mat(0.08, 0.08, 0.08, 0.95)
mparts = [box("body", 0, 0, 0.55, 4.0, 1.7, 0.55, mat(0.62, 0.07, 0.07, 0.35, 0.3)),
          box("cabin", -0.2, 0, 1.02, 2.0, 1.5, 0.45, mglass)]
for j, (wx, wy) in enumerate([(1.25, 0.85), (1.25, -0.85), (-1.25, 0.85), (-1.25, -0.85)]):
    mparts.append(f'<visual name="w{j}"><pose>{wx} {wy} 0.32 1.5708 0 0</pose>'
                  f'<geometry><cylinder><radius>0.32</radius><length>0.24</length></cylinder>'
                  f'</geometry>{mtyre}</visual>')
inertia = ('<inertial><mass>1000</mass><inertia><ixx>500</ixx><iyy>1500</iyy><izz>1800</izz>'
           '<ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia></inertial>')
MOVING_CAR = (
    '    <!-- ==== moving target: a red car lapped in a circle for the dynamic-chase demo ==== -->\n'
    f'    <model name="red_car_moving"><pose degrees="true">{mcx + mR:.0f} {mcy:.0f} 0 0 0 90</pose>\n'
    f'      <link name="l"><gravity>false</gravity>{inertia}{"".join(mparts)}</link>\n'
    '      <plugin filename="gz-sim-velocity-control-system" name="gz::sim::systems::VelocityControl">\n'
    f'        <initial_linear>{mv} 0 0</initial_linear>'
    f'<initial_angular>0 0 {mv / mR}</initial_angular>\n'
    '      </plugin>\n'
    '    </model>\n')
for i, (x, y, r) in enumerate(bushes):
    g = 0.30 + (i % 3) * 0.05
    scenery.append(f'    <model name="bush_{i}"><static>true</static>'
                   f'<pose>{x} {y} {r*0.45:.2f} 0 0 0</pose><link name="l"><visual name="v">'
                   f'<geometry><ellipsoid><radii>{r} {r*0.9:.2f} {r*0.6:.2f}</radii></ellipsoid>'
                   f'</geometry>{mat(0.12, g, 0.10, 0.95)}</visual></link></model>')
for i, (x, y, r) in enumerate(rocks):
    s = 0.42 + (i % 3) * 0.05
    scenery.append(f'    <model name="rock_{i}"><static>true</static>'
                   f'<pose degrees="true">{x} {y} {r*0.35:.2f} 0 0 {(i*53) % 180}</pose>'
                   f'<link name="l"><visual name="v">'
                   f'<geometry><ellipsoid><radii>{r} {r*0.75:.2f} {r*0.5:.2f}</radii></ellipsoid>'
                   f'</geometry>{mat(s, s, s + 0.02, 0.98)}</visual></link></model>')

with open(WORLD, "w") as fh:
    fh.write(HEADER + "\n" + "\n".join(grass) + "\n\n" + "\n".join(scenery) + "\n"
             + PERSON + MOVING_CAR + FOOTER)
print(f"wrote iris_field_vision.sdf: {N*N} grass tiles, {len(trees)} trees, {len(buildings)} "
      f"buildings (solid), {len(roads)} roads, {len(cars)} static cars, {len(towers)} towers, "
      f"{len(poles)} poles, {len(walls)} walls, 1 pond, 1 walking person, 1 moving car")
